### ISSUE TITLE
Crash with Extended Industrialization machine

### ISSUE THREAD

**Issue by WhitePhant0m** [TheStaticVoid/MI-Sound-Addon#11]
[Crashlog](https://mclo.gs/QqrAudk)
[Extended Industrialization](https://www.curseforge.com/minecraft/mc-mods/extended-industrialization)

**Comment by TheStaticVoid** [comment]
Might be an issue with how Tesseract messes with the recipe handlers. I'll look into this further.

**Comment by Swedz** [comment]
This should have been fixed in Tesseract 1.2.2, let me know if thats not the case

**Comment by WhitePhant0m** [comment]
Can confirm that Tesseract 1.2.2 fixes this.
